// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef _3D_PRINTER_UI_H
#define _3D_PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SHARED THEME ////////////////////
#define SBX_COL_BG      0x121821   /* app background (blends with nav_bar) */
#define SBX_COL_HEADER  0x1E2838   /* rounded header fill                  */
#define SBX_COL_ACCENT  0x00D2FF   /* cyan accent                          */

/* Cyan active-tab accent bar on the left edge of the nav sidebar.
   section: 0 = HOME, 1 = INFO, 2 = CONFIG (each nav slot is 160 px tall). */
static inline void sbx_nav_accent(lv_obj_t * navbar, int section)
{
    lv_obj_t * a = lv_obj_create(navbar);
    lv_obj_remove_style_all(a);
    lv_obj_set_size(a, 5, 92);
    lv_obj_set_pos(a, 0, section * 160 + 34);
    lv_obj_set_style_radius(a, 3, 0);
    lv_obj_set_style_bg_color(a, lv_color_hex(SBX_COL_ACCENT), 0);
    lv_obj_set_style_bg_opa(a, 255, 0);
}

///////////////////// SCREENS ////////////////////

#include "ui_screeninfo.h"
#include "ui_screenhome.h"
#include "ui_screenconfig.h"

///////////////////// VARIABLES ////////////////////
#include "ui_screenconfig.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * OpaOn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * OpaOff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuOut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenOut_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_pc_png);    // assets/icn_pc.png
LV_IMG_DECLARE(ui_img_icn_usb_png);    // assets/icn_usb.png
LV_IMG_DECLARE(ui_img_btn_print_v2_png);    // assets/btn_print_v2.png
LV_IMG_DECLARE(ui_img_btn_setting_png);    // assets/btn_setting.png
LV_IMG_DECLARE(ui_img_btn_main_off_png);    // assets/btn_main_off.png
LV_IMG_DECLARE(ui_img_btn_main_on_png);    // assets/btn_main_on.png
LV_IMG_DECLARE(ui_img_btn_print_v1_png);    // assets/btn_print_v1.png
LV_IMG_DECLARE(ui_img_btn_move_png);    // assets/btn_move.png
LV_IMG_DECLARE(ui_img_print_view_bg_png);    // assets/print_view_bg.png
LV_IMG_DECLARE(ui_img_print_view_front_png);    // assets/print_view_front.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets/icn_time_2.png
LV_IMG_DECLARE(ui_img_btn_print_down_v2_png);    // assets/btn_print_down_v2.png
LV_IMG_DECLARE(ui_img_btn_print_top_off_png);    // assets/btn_print_top_off.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png

// FONTS  (built-in Montserrat only: 16, 36, 48)
LV_IMG_DECLARE(ui_img_nav_bar);   // left sidebar (replaces the full-screen bg)

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
