// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void cancel_pwd(lv_event_t * e);
void confirm_pwd(lv_event_t * e);
void opencalendar(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
