// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "ui.h"
#include "steribox_app.h"

void cancel_pwd(lv_event_t * e)
{
    (void)e;
    steribox_ev_cancel_pwd();
}

void confirm_pwd(lv_event_t * e)
{
    (void)e;
    steribox_ev_confirm_pwd();
}

void opencalendar(lv_event_t * e)
{
    /*Wired to the Save button in SquareLine: saves date/time config*/
    (void)e;
    steribox_ev_save_config();
}
