// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef UI_SCREENCONFIG_H
#define UI_SCREENCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenconfig
extern void ui_screenconfig_screen_init(void);
extern void ui_screenconfig_screen_destroy(void);
extern void ui_event_screenconfig(lv_event_t * e);
extern lv_obj_t * ui_screenconfig;
extern lv_obj_t * ui_Image2;
extern void ui_event_BTN_Menu_Setting_S3(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Setting_S3;
extern void ui_event_BTN_Menu_Move_S7(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Move_S7;
extern lv_obj_t * ui_BTN_Menu_Move_S6;
extern lv_obj_t * ui_popup;
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern void ui_event_pwd(lv_event_t * e);
extern lv_obj_t * ui_pwd;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_mainbody;
extern lv_obj_t * ui_TextArea5;     /* date textarea            */
extern void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_Roller1;       /* hour roller              */
extern lv_obj_t * ui_Roller2;       /* minute roller            */
extern lv_obj_t * ui_Roller3;       /* AM/PM roller             */
extern lv_obj_t * ui_layer2;        /* calendar overlay         */
extern lv_obj_t * ui_Calendar2;
/* Lamp arc gauges */
extern lv_obj_t * ui_arc_lamp1;
extern lv_obj_t * ui_arc_lamp2;
/* Lamp status labels */
extern lv_obj_t * ui_lamp1_hours_label;
extern lv_obj_t * ui_lamp2_hours_label;
extern lv_obj_t * ui_lamp1_pct_label;
extern lv_obj_t * ui_lamp2_pct_label;
/* Reset buttons */
extern lv_obj_t * ui_lampe_1;       /* lamp1 reset button       */
extern lv_obj_t * ui_lampe_2;       /* lamp2 reset button       */
/* Confirmation popup */
extern lv_obj_t * ui_confirm_popup;
extern lv_obj_t * ui_confirm_label;
extern lv_obj_t * ui_confirm_yes;
extern lv_obj_t * ui_confirm_no;
/* Apply Changes button */
extern lv_obj_t * ui_BTN_Apply;

/* stubs – widgets removed in redesign but referenced in app code */
extern lv_obj_t * ui_IMG_USB6;
extern lv_obj_t * ui_Label_Time5;
extern lv_obj_t * ui_Panel_Header5;
extern lv_obj_t * ui_Label_Header5;


// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
