// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenhome
extern void ui_screenhome_screen_init(void);
extern void ui_screenhome_screen_destroy(void);
extern lv_obj_t * ui_screenhome;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_navBar;
extern lv_obj_t * ui_BTN_Menu_Print_S4;
extern void ui_event_BTN_Menu_Move_S4(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Move_S4;
extern void ui_event_BTN_Menu_Move_S1(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Move_S1;
extern lv_obj_t * ui_Panel_Header3;
extern lv_obj_t * ui_Label_Header3;
extern lv_obj_t * ui_Label_Time3;
extern lv_obj_t * ui_IMG_Wifi3;
extern lv_obj_t * ui_IMG_PC3;
extern lv_obj_t * ui_IMG_USB3;
extern lv_obj_t * ui_S1_Content_Panel3;
extern lv_obj_t * ui_Panel8;
extern void ui_event_Slider_Print_View1(lv_event_t * e);
extern lv_obj_t * ui_Slider_Print_View1;
extern lv_obj_t * ui_Number_Print1;
extern lv_obj_t * ui_Display_Time_S2;
extern lv_obj_t * ui_Label_Printing_Time_4;
extern lv_obj_t * ui_IMG_Tine_4;
extern lv_obj_t * ui_Label_Time_5;
extern lv_obj_t * ui_Label_Time_1;
extern lv_obj_t * ui_Label_Time_2;
extern lv_obj_t * ui_Panel_Slider2;
extern void ui_event_Slider_Print_Speed2(lv_event_t * e);
extern lv_obj_t * ui_Slider_Print_Speed2;
extern lv_obj_t * ui_Panel_Buttons_S2;
extern lv_obj_t * ui_BTN_Pause1;
extern lv_obj_t * ui_BTN_Pause_Top1;
extern lv_obj_t * ui_Image_Pause1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Chart3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

