// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "ui.h"

lv_obj_t * ui_screeninfo = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Panel_Header1 = NULL;
lv_obj_t * ui_Label_Header1 = NULL;
lv_obj_t * ui_Label_Time1 = NULL;
lv_obj_t * ui_IMG_Wifi1 = NULL;
lv_obj_t * ui_IMG_PC1 = NULL;
lv_obj_t * ui_IMG_USB1 = NULL;
lv_obj_t * ui_BTN_Menu_Move_S2 = NULL;
lv_obj_t * ui_BTN_Menu_Setting_S2 = NULL;
lv_obj_t * ui_BTN_Menu_Move_S5 = NULL;
lv_obj_t * ui_S1_Content_Panel4 = NULL;
lv_obj_t * ui_Display_Pos_y1 = NULL;
lv_obj_t * ui_Label_Z_Position_Number1 = NULL;
lv_obj_t * ui_Label_Z_Position1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Display_Pos_y2 = NULL;
lv_obj_t * ui_Label_Z_Position_Number2 = NULL;
lv_obj_t * ui_Label_Z_Position2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Display_Pos_y3 = NULL;
lv_obj_t * ui_Label_Z_Position_Number3 = NULL;
lv_obj_t * ui_Label_Z_Position3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Display_Pos_y4 = NULL;
lv_obj_t * ui_Label_Z_Position_Number4 = NULL;
lv_obj_t * ui_Label_Z_Position4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Display_Pos_y5 = NULL;
lv_obj_t * ui_Label_Z_Position_Number5 = NULL;
lv_obj_t * ui_Label_Z_Position5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Display_Pos_y6 = NULL;
lv_obj_t * ui_Label_Z_Position_Number6 = NULL;
lv_obj_t * ui_Label_Z_Position6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_BTN_Reset2 = NULL;
lv_obj_t * ui_Label_Reset2 = NULL;
lv_obj_t * ui_IMG_USB4 = NULL;
lv_obj_t * ui_IMG_PC4 = NULL;
lv_obj_t * ui_BTN_Reset1 = NULL;
lv_obj_t * ui_Label_Reset1 = NULL;
// event funtions
void ui_event_BTN_Menu_Setting_S2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenhome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenhome_screen_init);
    }
}

void ui_event_BTN_Menu_Move_S5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenconfig, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenconfig_screen_init);
    }
}

// build funtions

void ui_screeninfo_screen_init(void)
{
    ui_screeninfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screeninfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_screeninfo, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_screeninfo, lv_color_hex(SBX_COL_BG), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screeninfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = NULL;

    /* Left nav sidebar image + active accent (INFO) */
    lv_obj_t * navImg = lv_img_create(ui_screeninfo);
    lv_img_set_src(navImg, &ui_img_nav_bar);
    lv_obj_set_pos(navImg, 0, 0);
    sbx_nav_accent(ui_screeninfo, 1);

    ui_Panel_Header1 = lv_obj_create(ui_screeninfo);
    lv_obj_set_width(ui_Panel_Header1, 712);
    lv_obj_set_height(ui_Panel_Header1, 45);
    lv_obj_set_x(ui_Panel_Header1, -6);
    lv_obj_set_y(ui_Panel_Header1, 6);
    lv_obj_set_align(ui_Panel_Header1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header1, lv_color_hex(SBX_COL_HEADER), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel_Header1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header1 = lv_label_create(ui_Panel_Header1);
    lv_obj_set_width(ui_Label_Header1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header1, "Info");
    lv_obj_set_style_text_color(ui_Label_Header1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Live clock (RTC), driven by steribox_app.c */
    ui_Label_Time1 = lv_label_create(ui_Panel_Header1);
    lv_obj_set_width(ui_Label_Time1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_Time1, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label_Time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Time1, "00:00");
    lv_obj_set_style_text_color(ui_Label_Time1, lv_color_hex(0xC2CBDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Printer (PC) link indicator */
    ui_IMG_PC1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_PC1, &ui_img_icn_pc_png);
    lv_obj_set_width(ui_IMG_PC1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC1, 0);
    lv_obj_set_y(ui_IMG_PC1, 0);
    lv_obj_set_align(ui_IMG_PC1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    /* USB (export) indicator */
    ui_IMG_USB1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_USB1, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB1, -46);
    lv_obj_set_y(ui_IMG_USB1, 0);
    lv_obj_set_align(ui_IMG_USB1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Menu_Move_S2 = lv_img_create(ui_screeninfo);
    lv_img_set_src(ui_BTN_Menu_Move_S2, &ui_img_btn_print_v2_png);
    lv_obj_set_width(ui_BTN_Menu_Move_S2, 79);
    lv_obj_set_height(ui_BTN_Menu_Move_S2, 160);
    lv_obj_set_x(ui_BTN_Menu_Move_S2, 0);
    lv_obj_set_y(ui_BTN_Menu_Move_S2, 160);
    lv_obj_add_flag(ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTN_Menu_Move_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  /* icon shown by nav_bar */

    ui_BTN_Menu_Setting_S2 = lv_img_create(ui_screeninfo);
    lv_img_set_src(ui_BTN_Menu_Setting_S2, &ui_img_btn_setting_png);
    lv_obj_set_width(ui_BTN_Menu_Setting_S2, 79);
    lv_obj_set_height(ui_BTN_Menu_Setting_S2, 160);
    lv_obj_add_flag(ui_BTN_Menu_Setting_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Setting_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTN_Menu_Setting_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Menu_Move_S5 = lv_img_create(ui_screeninfo);
    lv_img_set_src(ui_BTN_Menu_Move_S5, &ui_img_btn_setting_png);
    lv_obj_set_width(ui_BTN_Menu_Move_S5, 79);
    lv_obj_set_height(ui_BTN_Menu_Move_S5, 160);
    lv_obj_set_x(ui_BTN_Menu_Move_S5, 0);
    lv_obj_set_y(ui_BTN_Menu_Move_S5, 320);
    lv_obj_add_flag(ui_BTN_Menu_Move_S5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Move_S5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTN_Menu_Move_S5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1_Content_Panel4 = lv_obj_create(ui_screeninfo);
    lv_obj_set_width(ui_S1_Content_Panel4, 720);
    lv_obj_set_height(ui_S1_Content_Panel4, 476);
    lv_obj_set_x(ui_S1_Content_Panel4, 0);
    lv_obj_set_y(ui_S1_Content_Panel4, 7);
    lv_obj_set_align(ui_S1_Content_Panel4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel4,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_S1_Content_Panel4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_S1_Content_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y1 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y1, 298);
    lv_obj_set_height(ui_Display_Pos_y1, 79);
    lv_obj_set_x(ui_Display_Pos_y1, 40);
    lv_obj_set_y(ui_Display_Pos_y1, 60);
    lv_obj_clear_flag(ui_Display_Pos_y1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number1 = lv_label_create(ui_Display_Pos_y1);
    lv_obj_set_width(ui_Label_Z_Position_Number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number1, -34);
    lv_obj_set_y(ui_Label_Z_Position_Number1, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number1, "30*C");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position1 = lv_label_create(ui_Display_Pos_y1);
    lv_obj_set_width(ui_Label_Z_Position1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position1, 30);
    lv_obj_set_y(ui_Label_Z_Position1, 0);
    lv_obj_set_align(ui_Label_Z_Position1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position1, "Temp");
    lv_obj_set_style_text_color(ui_Label_Z_Position1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Display_Pos_y1);
    lv_obj_set_width(ui_Panel1, 2);
    lv_obj_set_height(ui_Panel1, 32);
    lv_obj_set_x(ui_Panel1, 18);
    lv_obj_set_y(ui_Panel1, 2);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y2 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y2, 298);
    lv_obj_set_height(ui_Display_Pos_y2, 79);
    lv_obj_set_x(ui_Display_Pos_y2, 370);
    lv_obj_set_y(ui_Display_Pos_y2, 60);
    lv_obj_clear_flag(ui_Display_Pos_y2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number2 = lv_label_create(ui_Display_Pos_y2);
    lv_obj_set_width(ui_Label_Z_Position_Number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number2, -39);
    lv_obj_set_y(ui_Label_Z_Position_Number2, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number2, "20%");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position2 = lv_label_create(ui_Display_Pos_y2);
    lv_obj_set_width(ui_Label_Z_Position2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position2, 32);
    lv_obj_set_y(ui_Label_Z_Position2, 0);
    lv_obj_set_align(ui_Label_Z_Position2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position2, "Hum");
    lv_obj_set_style_text_color(ui_Label_Z_Position2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Display_Pos_y2);
    lv_obj_set_width(ui_Panel3, 2);
    lv_obj_set_height(ui_Panel3, 32);
    lv_obj_set_x(ui_Panel3, 18);
    lv_obj_set_y(ui_Panel3, 2);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y3 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y3, 298);
    lv_obj_set_height(ui_Display_Pos_y3, 79);
    lv_obj_set_x(ui_Display_Pos_y3, 370);
    lv_obj_set_y(ui_Display_Pos_y3, 160);
    lv_obj_clear_flag(ui_Display_Pos_y3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y3, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y3, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number3 = lv_label_create(ui_Display_Pos_y3);
    lv_obj_set_width(ui_Label_Z_Position_Number3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number3, -21);
    lv_obj_set_y(ui_Label_Z_Position_Number3, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number3, "expire");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number3, lv_color_hex(0xFF0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position3 = lv_label_create(ui_Display_Pos_y3);
    lv_obj_set_width(ui_Label_Z_Position3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position3, 36);
    lv_obj_set_y(ui_Label_Z_Position3, 1);
    lv_obj_set_align(ui_Label_Z_Position3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position3, "L2");
    lv_obj_set_style_text_color(ui_Label_Z_Position3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Display_Pos_y3);
    lv_obj_set_width(ui_Panel4, 2);
    lv_obj_set_height(ui_Panel4, 32);
    lv_obj_set_x(ui_Panel4, -46);
    lv_obj_set_y(ui_Panel4, 2);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y4 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y4, 298);
    lv_obj_set_height(ui_Display_Pos_y4, 79);
    lv_obj_set_x(ui_Display_Pos_y4, 370);
    lv_obj_set_y(ui_Display_Pos_y4, 260);
    lv_obj_clear_flag(ui_Display_Pos_y4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y4, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y4, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number4 = lv_label_create(ui_Display_Pos_y4);
    lv_obj_set_width(ui_Label_Z_Position_Number4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number4, -50);
    lv_obj_set_y(ui_Label_Z_Position_Number4, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number4, "125");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number4, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position4 = lv_label_create(ui_Display_Pos_y4);
    lv_obj_set_width(ui_Label_Z_Position4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position4, 25);
    lv_obj_set_y(ui_Label_Z_Position4, 0);
    lv_obj_set_align(ui_Label_Z_Position4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position4, "Cycles");
    lv_obj_set_style_text_color(ui_Label_Z_Position4, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Display_Pos_y4);
    lv_obj_set_width(ui_Panel5, 2);
    lv_obj_set_height(ui_Panel5, 32);
    lv_obj_set_x(ui_Panel5, 58);
    lv_obj_set_y(ui_Panel5, 2);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y5 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y5, 298);
    lv_obj_set_height(ui_Display_Pos_y5, 79);
    lv_obj_set_x(ui_Display_Pos_y5, 40);
    lv_obj_set_y(ui_Display_Pos_y5, 260);
    lv_obj_clear_flag(ui_Display_Pos_y5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y5, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y5, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number5 = lv_label_create(ui_Display_Pos_y5);
    lv_obj_set_width(ui_Label_Z_Position_Number5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number5, -13);
    lv_obj_set_y(ui_Label_Z_Position_Number5, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number5, "1255 h");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number5, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position5 = lv_label_create(ui_Display_Pos_y5);
    lv_obj_set_width(ui_Label_Z_Position5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position5, 36);
    lv_obj_set_y(ui_Label_Z_Position5, 0);
    lv_obj_set_align(ui_Label_Z_Position5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position5, "Total");
    lv_obj_set_style_text_color(ui_Label_Z_Position5, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Display_Pos_y5);
    lv_obj_set_width(ui_Panel6, 2);
    lv_obj_set_height(ui_Panel6, 32);
    lv_obj_set_x(ui_Panel6, 36);
    lv_obj_set_y(ui_Panel6, 2);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y6 = lv_obj_create(ui_S1_Content_Panel4);
    lv_obj_set_width(ui_Display_Pos_y6, 298);
    lv_obj_set_height(ui_Display_Pos_y6, 79);
    lv_obj_set_x(ui_Display_Pos_y6, 40);
    lv_obj_set_y(ui_Display_Pos_y6, 160);
    lv_obj_clear_flag(ui_Display_Pos_y6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y6, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y6, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number6 = lv_label_create(ui_Display_Pos_y6);
    lv_obj_set_width(ui_Label_Z_Position_Number6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number6, -12);
    lv_obj_set_y(ui_Label_Z_Position_Number6, 0);
    lv_obj_set_align(ui_Label_Z_Position_Number6, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Z_Position_Number6, "50 h");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number6, lv_color_hex(0xFF7405), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position6 = lv_label_create(ui_Display_Pos_y6);
    lv_obj_set_width(ui_Label_Z_Position6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position6, 38);
    lv_obj_set_y(ui_Label_Z_Position6, 2);
    lv_obj_set_align(ui_Label_Z_Position6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Z_Position6, "L1");
    lv_obj_set_style_text_color(ui_Label_Z_Position6, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Display_Pos_y6);
    lv_obj_set_width(ui_Panel7, 2);
    lv_obj_set_height(ui_Panel7, 32);
    lv_obj_set_x(ui_Panel7, -46);
    lv_obj_set_y(ui_Panel7, 2);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Reset2 = lv_imgbtn_create(ui_S1_Content_Panel4);
    lv_imgbtn_set_src(ui_BTN_Reset2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Reset2, 66);
    lv_obj_set_width(ui_BTN_Reset2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Reset2, -454);
    lv_obj_set_y(ui_BTN_Reset2, 385);
    lv_obj_set_align(ui_BTN_Reset2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_BTN_Reset2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Reset2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Reset2, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Reset2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Reset2, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Reset2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Reset2 = lv_label_create(ui_BTN_Reset2);
    lv_obj_set_width(ui_Label_Reset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Reset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Reset2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Reset2, "Export");
    lv_obj_set_style_text_color(ui_Label_Reset2, lv_color_hex(0x00CAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Reset2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Reset2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Reset2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_USB4 = lv_img_create(ui_S1_Content_Panel4);
    lv_img_set_src(ui_IMG_USB4, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB4, -623);
    lv_obj_set_y(ui_IMG_USB4, 178);
    lv_obj_set_align(ui_IMG_USB4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_angle(ui_IMG_USB4, 900);

    ui_IMG_PC4 = lv_img_create(ui_S1_Content_Panel4);
    lv_img_set_src(ui_IMG_PC4, &ui_img_icn_pc_png);
    lv_obj_set_width(ui_IMG_PC4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC4, -287);
    lv_obj_set_y(ui_IMG_PC4, 182);
    lv_obj_set_align(ui_IMG_PC4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Reset1 = lv_imgbtn_create(ui_S1_Content_Panel4);
    lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Reset1, 66);
    lv_obj_set_width(ui_BTN_Reset1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Reset1, -114);
    lv_obj_set_y(ui_BTN_Reset1, 386);
    lv_obj_set_align(ui_BTN_Reset1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Reset1 = lv_label_create(ui_BTN_Reset1);
    lv_obj_set_width(ui_Label_Reset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Reset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Reset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Reset1, "PRINT");
    lv_obj_set_style_text_align(ui_Label_Reset1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Reset1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_Menu_Setting_S2, ui_event_BTN_Menu_Setting_S2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Menu_Move_S5, ui_event_BTN_Menu_Move_S5, LV_EVENT_ALL, NULL);

}

void ui_screeninfo_screen_destroy(void)
{
    if(ui_screeninfo) lv_obj_del(ui_screeninfo);

    // NULL screen variables
    ui_screeninfo = NULL;
    ui_Image5 = NULL;
    ui_Panel_Header1 = NULL;
    ui_Label_Header1 = NULL;
    ui_Label_Time1 = NULL;
    ui_IMG_Wifi1 = NULL;
    ui_IMG_PC1 = NULL;
    ui_IMG_USB1 = NULL;
    ui_BTN_Menu_Move_S2 = NULL;
    ui_BTN_Menu_Setting_S2 = NULL;
    ui_BTN_Menu_Move_S5 = NULL;
    ui_S1_Content_Panel4 = NULL;
    ui_Display_Pos_y1 = NULL;
    ui_Label_Z_Position_Number1 = NULL;
    ui_Label_Z_Position1 = NULL;
    ui_Panel1 = NULL;
    ui_Display_Pos_y2 = NULL;
    ui_Label_Z_Position_Number2 = NULL;
    ui_Label_Z_Position2 = NULL;
    ui_Panel3 = NULL;
    ui_Display_Pos_y3 = NULL;
    ui_Label_Z_Position_Number3 = NULL;
    ui_Label_Z_Position3 = NULL;
    ui_Panel4 = NULL;
    ui_Display_Pos_y4 = NULL;
    ui_Label_Z_Position_Number4 = NULL;
    ui_Label_Z_Position4 = NULL;
    ui_Panel5 = NULL;
    ui_Display_Pos_y5 = NULL;
    ui_Label_Z_Position_Number5 = NULL;
    ui_Label_Z_Position5 = NULL;
    ui_Panel6 = NULL;
    ui_Display_Pos_y6 = NULL;
    ui_Label_Z_Position_Number6 = NULL;
    ui_Label_Z_Position6 = NULL;
    ui_Panel7 = NULL;
    ui_BTN_Reset2 = NULL;
    ui_Label_Reset2 = NULL;
    ui_IMG_USB4 = NULL;
    ui_IMG_PC4 = NULL;
    ui_BTN_Reset1 = NULL;
    ui_Label_Reset1 = NULL;

}
