// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef UI_SCREENINFO_H
#define UI_SCREENINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screeninfo
extern void ui_screeninfo_screen_init(void);
extern void ui_screeninfo_screen_destroy(void);
extern lv_obj_t * ui_screeninfo;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel_Header1;
extern lv_obj_t * ui_Label_Header1;
extern lv_obj_t * ui_Label_Time1;
extern lv_obj_t * ui_IMG_Wifi1;
extern lv_obj_t * ui_IMG_PC1;
extern lv_obj_t * ui_IMG_USB1;
extern lv_obj_t * ui_BTN_Menu_Move_S2;
extern void ui_event_BTN_Menu_Setting_S2(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Setting_S2;
extern void ui_event_BTN_Menu_Move_S5(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Move_S5;
extern lv_obj_t * ui_S1_Content_Panel4;
extern lv_obj_t * ui_Display_Pos_y1;
extern lv_obj_t * ui_Label_Z_Position_Number1;
extern lv_obj_t * ui_Label_Z_Position1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Display_Pos_y2;
extern lv_obj_t * ui_Label_Z_Position_Number2;
extern lv_obj_t * ui_Label_Z_Position2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Display_Pos_y3;
extern lv_obj_t * ui_Label_Z_Position_Number3;
extern lv_obj_t * ui_Label_Z_Position3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Display_Pos_y4;
extern lv_obj_t * ui_Label_Z_Position_Number4;
extern lv_obj_t * ui_Label_Z_Position4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Display_Pos_y5;
extern lv_obj_t * ui_Label_Z_Position_Number5;
extern lv_obj_t * ui_Label_Z_Position5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Display_Pos_y6;
extern lv_obj_t * ui_Label_Z_Position_Number6;
extern lv_obj_t * ui_Label_Z_Position6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_BTN_Reset2;
extern lv_obj_t * ui_Label_Reset2;
extern lv_obj_t * ui_IMG_USB4;
extern lv_obj_t * ui_IMG_PC4;
extern lv_obj_t * ui_BTN_Reset1;
extern lv_obj_t * ui_Label_Reset1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

